services:

  db:
    image: postgres:15-alpine
    container_name: securebank-db
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: securebank-app
    environment:
      DB_URL: jdbc:postgresql://db:5432/securebank
      DB_USERNAME: postgres
      DB_PASSWORD: 12345
      JWT_SECRET: c2VjdXJlYmFua3N1cGVyc2VjcmV0a2V5bWluaW11bTI1NmJpdHNwb3VyaHMyNTZhbGdvcml0aG0=
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: